import { Scene } from 'phaser'
 
/* This file is autogenerated by scripts/load-images.js*/ 
export const preloadFunctions: Record<string, (scene: Scene) => void> = {
  'procreate-test-3': function (scene: Scene) {
    scene.load.tilemapTiledJSON('procreate-test-3', 'tilemaps/procreate-test-3.json')
    scene.load.image('Tile-set2', '../../../Tile-set2.png')
  },
  'procreate-test2': function (scene: Scene) {
    scene.load.tilemapTiledJSON('procreate-test2', 'tilemaps/procreate-test2.json')
    scene.load.image('Tile-set2', '../../../Tile-set2.png')
  },
  'residence': function (scene: Scene) {
    scene.load.tilemapTiledJSON('residence', 'tilemaps/residence.json')
    scene.load.image('isometric-grid', 'tilemaps/isometric-grid.png')
  },
  'shop': function (scene: Scene) {
    scene.load.tilemapTiledJSON('shop', 'tilemaps/shop.json')
    scene.load.image('isometric-grid', 'tilemaps/isometric-grid.png')
  },
  'town': function (scene: Scene) {
    scene.load.tilemapTiledJSON('town', 'tilemaps/town.json')
    scene.load.image('isometric-grid', 'tilemaps/isometric-grid.png')
    scene.load.image('house', 'images/house.png')
    scene.load.image('charlie', 'images/charlie.png')
    scene.load.image('player-temp', 'images/player-temp.png')
  },
}